// Copyright 2026 Rockyljewell
// SPDX-License-Identifier: Apache-2.0
// Bundles src/engine/worker.ts (with the zxing-wasm reader glue) into a single IIFE and
// writes it as a string constant, so the SDK can start the worker from a Blob URL.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BANNER } from "./banner.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const result = await build({
  entryPoints: [resolve(root, "src/engine/worker.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "none",
  banner: { js: BANNER },
  logLevel: "warning",
});
const code = result.outputFiles[0].text;
mkdirSync(resolve(root, "src/generated"), { recursive: true });
writeFileSync(
  resolve(root, "src/generated/worker-source.ts"),
  `// Generated by scripts/build-worker.mjs. Do not edit.\nexport const WORKER_SOURCE: string = ${JSON.stringify(code)};\n`,
);
console.log(`[qrgen] worker bundled (${(code.length / 1024).toFixed(1)} KiB)`);
